"""empty message

Revision ID: 63d86aa1b6a2
Revises: e4402d47c01e
Create Date: 2022-07-23 21:33:47.414829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d86aa1b6a2'
down_revision = 'e4402d47c01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwdreset_hashedtoken', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwdreset_hashedtoken')
    # ### end Alembic commands ###
